name: Invoke Lambda Function

on:
  issues:
    types:
      - opened

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Invoke Lambda Function
        if: contains(github.event.issue.title, 'PROVA')
        run: |
          curl -X GET -H "Authorization: Bearer " \
            -H "Content-Type: application/json" \
            https://aefnyrpj35isimutchazova3sq0vjpvu.lambda-url.us-east-1.on.aws/?GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}&start_date=2022-01-01&end_date=2022-01-31&owner=smarko82&repo=prova
